# Source: cluster-api-aws/templates/job-check.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: 31460d74-f77d-453d-8b4c-42e016ce3d4c-capi-aws-check
  namespace: 31460d74-f77d-453d-8b4c-42e016ce3d4c
spec:
  template:
    metadata:
      name: 31460d74-f77d-453d-8b4c-42e016ce3d4c-capi-aws
    spec:
      serviceAccountName: 31460d74-f77d-453d-8b4c-42e016ce3d4c-capi-aws
      containers:
      - name: wait-for-ready
        image: "ghcr.io/openinfradev/python_kubectl_argo:v1.1.0"
        imagePullPolicy: IfNotPresent
        command:
        - timeout 
        - 5m
        - /wait_for_kubeconfig.sh  
        - 31460d74-f77d-453d-8b4c-42e016ce3d4c
        - 31460d74-f77d-453d-8b4c-42e016ce3d4c
        volumeMounts:
        - name: vol
          subPath: wait_for_kubeconfig.sh
          mountPath: /wait_for_kubeconfig.sh
      volumes:
      - name: vol
        configMap:
          name: 31460d74-f77d-453d-8b4c-42e016ce3d4c-capi-aws
          defaultMode: 0555
      restartPolicy: OnFailure
